# Generated by Django 4.1.13 on 2025-12-02 12:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, verbose_name='Номер счета')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Баланс')),
                ('account_type', models.CharField(choices=[('main', 'Основной'), ('secondary', 'Дополнительный')], default='main', max_length=20, verbose_name='Тип счета')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_date', models.DateTimeField(verbose_name='Дата и время события')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Напоминание отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Событие календаря',
                'verbose_name_plural': 'События календаря',
                'ordering': ['event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254, verbose_name='Email пользователя')),
                ('chat_id', models.CharField(db_index=True, max_length=255, verbose_name='ID чата')),
                ('title', models.CharField(default='Новый чат', max_length=500, verbose_name='Название чата')),
                ('messages', models.JSONField(default=list, verbose_name='Сообщения')),
                ('ai_actions', models.JSONField(default=list, verbose_name='Действия AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего сообщения')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Всего сообщений')),
                ('total_user_messages', models.IntegerField(default=0, verbose_name='Сообщений пользователя')),
                ('total_ai_messages', models.IntegerField(default=0, verbose_name='Сообщений AI')),
                ('total_actions', models.IntegerField(default=0, verbose_name='Всего действий')),
            ],
            options={
                'verbose_name': 'История чата',
                'verbose_name_plural': 'Истории чатов',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file_type', models.CharField(max_length=100, verbose_name='Тип файла (MIME)')),
                ('file_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Размер файла (байт)')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Зарплата')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Дата последней выплаты')),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Ежемесячно'), ('weekly', 'Еженедельно'), ('biweekly', 'Раз в две недели')], default='monthly', max_length=20, verbose_name='Периодичность выплат')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('hired_date', models.DateField(blank=True, null=True, verbose_name='Дата найма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('read', 'Прочитано'), ('replied', 'Отвечено'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_reply', models.TextField(blank=True, verbose_name='Ответ администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название папки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Папка инвентаризации',
                'verbose_name_plural': 'Папки инвентаризации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар инвентаризации',
                'verbose_name_plural': 'Товары инвентаризации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('debt', 'Задолженность'), ('calendar', 'Календарь'), ('salary', 'Зарплата'), ('system', 'Системное')], max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('related_event_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID связанного события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=20, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата операции')),
                ('pinned', models.BooleanField(default=False, verbose_name='Закреплен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts/%Y/%m/%d/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file_type', models.CharField(max_length=100, verbose_name='Тип файла')),
                ('file_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Размер файла (байт)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Файл чека',
                'verbose_name_plural': 'Файлы чеков',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('profit', 'Налог на прибыль'), ('vat', 'НДС'), ('property', 'Налог на имущество'), ('insurance', 'Страховые взносы')], max_length=50, verbose_name='Тип налога')),
                ('debt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Задолженность')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Базовая сумма')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней оплаты')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('transaction_date', models.DateTimeField(verbose_name='Дата перевода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255, verbose_name='Название организации')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная')], default='light', max_length=10, verbose_name='Тема оформления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('electricity', 'Электричество'), ('water', 'Вода'), ('heating', 'Отопление'), ('waste', 'Вывоз мусора'), ('security', 'Охрана'), ('internet', 'Интернет')], max_length=50, verbose_name='Тип услуги')),
                ('debt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Задолженность')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Базовая сумма')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней оплаты')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Коммунальная услуга',
                'verbose_name_plural': 'Коммунальные услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='chatrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос к AI', 'verbose_name_plural': 'Запросы к AI'},
        ),
        migrations.RemoveIndex(
            model_name='chatrequest',
            name='main_chatre_status_created_idx',
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='action',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='chat_history',
            field=models.JSONField(blank=True, default=list, verbose_name='История чата'),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='files_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='user_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные пользователя'),
        ),
        migrations.AddIndex(
            model_name='chatrequest',
            index=models.Index(fields=['user', 'status', '-created_at'], name='main_chatre_user_id_0d019b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrequest',
            index=models.Index(fields=['status', '-created_at'], name='main_chatre_status_86fa37_idx'),
        ),
        migrations.AddField(
            model_name='utility',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='main.account', verbose_name='Счет отправителя'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='main.account', verbose_name='Счет получателя'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='tax',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='receiptfile',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.receipt', verbose_name='Чек'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='main.inventoryfolder', verbose_name='Папка'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='inventoryfolder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_folders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='employeefolder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_folders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='employee',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='main.employeefolder', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Работодатель'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='utility',
            index=models.Index(fields=['user', 'is_active'], name='main_utilit_user_id_bb4ade_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='utility',
            unique_together={('user', 'utility_type')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_active', '-created_at'], name='main_userpr_is_acti_8bea6b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-transaction_date'], name='main_transa_user_id_ea6593_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_account', '-transaction_date'], name='main_transa_from_ac_095a42_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_account', '-transaction_date'], name='main_transa_to_acco_6dd2eb_idx'),
        ),
        migrations.AddIndex(
            model_name='tax',
            index=models.Index(fields=['user', 'is_active'], name='main_tax_user_id_aeb28b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together={('user', 'tax_type')},
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', '-date'], name='main_receip_user_id_418c91_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'operation_type', '-date'], name='main_receip_user_id_9cf42f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['pinned', '-date'], name='main_receip_pinned_763132_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='main_notifi_user_id_943615_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', '-created_at'], name='main_notifi_type_5b37b9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['user', '-created_at'], name='main_invent_user_id_4cc0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['folder', 'name'], name='main_invent_folder__435c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryfolder',
            index=models.Index(fields=['user', 'name'], name='main_invent_user_id_e9b0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackmessage',
            index=models.Index(fields=['user', '-created_at'], name='main_feedba_user_id_9e8dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackmessage',
            index=models.Index(fields=['status', '-created_at'], name='main_feedba_status_6dbd04_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefolder',
            index=models.Index(fields=['user', 'name'], name='main_employ_user_id_0b824c_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user', 'is_active'], name='main_employ_user_id_df8338_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['folder', 'fio'], name='main_employ_folder__559372_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_payment_date'], name='main_employ_last_pa_2bbd32_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', '-uploaded_at'], name='main_docume_user_id_703271_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_archived'], name='main_docume_is_arch_2005e3_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user', '-last_message_at'], name='main_chathi_user_id_8788fe_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user_email', '-last_message_at'], name='main_chathi_user_em_cc35a1_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['chat_id'], name='main_chathi_chat_id_50387f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'event_date'], name='main_calend_user_id_aadd2c_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_date', 'reminder_sent'], name='main_calend_event_d_9dd582_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', '-created_at'], name='main_accoun_user_id_2cc21c_idx'),
        ),
    ]
