# Generated by Django 4.2.26 on 2025-12-02 16:29

from django.db import migrations, models


def safe_remove_employee_folder_field(apps, schema_editor):
    """Безопасно удаляет поле folder из модели employee, если оно существует"""
    try:
        Employee = apps.get_model('main', 'Employee')
        if Employee:
            # Сначала удаляем индексы, которые используют поле folder
            try:
                schema_editor.execute("DROP INDEX IF EXISTS main_employ_folder__559372_idx;")
            except:
                pass
            # Затем удаляем поле, если оно существует
            if hasattr(Employee._meta, 'get_field'):
                try:
                    field = Employee._meta.get_field('folder')
                    schema_editor.remove_field(Employee, field)
                except:
                    # Поле не существует, пропускаем
                    pass
    except:
        # Модель не существует, пропускаем
        pass


def safe_remove_inventoryitem_folder_field(apps, schema_editor):
    """Безопасно удаляет поле folder из модели inventoryitem, если оно существует"""
    try:
        InventoryItem = apps.get_model('main', 'InventoryItem')
        if InventoryItem:
            # Сначала удаляем индексы, которые используют поле folder
            try:
                schema_editor.execute("DROP INDEX IF EXISTS main_invent_folder__435c8e_idx;")
            except:
                pass
            # Затем удаляем поле, если оно существует
            if hasattr(InventoryItem._meta, 'get_field'):
                try:
                    field = InventoryItem._meta.get_field('folder')
                    schema_editor.remove_field(InventoryItem, field)
                except:
                    # Поле не существует, пропускаем
                    pass
    except:
        # Модель не существует, пропускаем
        pass


def safe_remove_transaction_fields(apps, schema_editor):
    """Безопасно удаляет поля from_account и to_account из модели Transaction"""
    try:
        Transaction = apps.get_model('main', 'Transaction')
        if Transaction:
            # Сначала удаляем индексы, которые используют эти поля
            try:
                schema_editor.execute("DROP INDEX IF EXISTS main_transa_from_ac_095a42_idx;")
            except:
                pass
            try:
                schema_editor.execute("DROP INDEX IF EXISTS main_transa_to_acco_6dd2eb_idx;")
            except:
                pass
            
            # Затем удаляем поля, если они существуют
            if hasattr(Transaction._meta, 'get_field'):
                # Удаляем from_account
                try:
                    field = Transaction._meta.get_field('from_account')
                    schema_editor.remove_field(Transaction, field)
                except:
                    pass
                
                # Удаляем to_account
                try:
                    field = Transaction._meta.get_field('to_account')
                    schema_editor.remove_field(Transaction, field)
                except:
                    pass
    except:
        # Модель не существует, пропускаем
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_calendarevent_chathistory_document_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        # Используем RunPython для безопасного удаления поля folder из employee
        migrations.RunPython(
            safe_remove_employee_folder_field,
            migrations.RunPython.noop,  # Обратная миграция ничего не делает
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employeefolder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedbackmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventoryfolder',
            name='user',
        ),
        # Используем RunPython для безопасного удаления поля folder из inventoryitem
        migrations.RunPython(
            safe_remove_inventoryitem_folder_field,
            migrations.RunPython.noop,  # Обратная миграция ничего не делает
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='receiptfile',
            name='receipt',
        ),
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tax',
            name='user',
        ),
        # Используем RunPython для безопасного удаления полей from_account и to_account из Transaction
        migrations.RunPython(
            safe_remove_transaction_fields,
            migrations.RunPython.noop,  # Обратная миграция ничего не делает
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='utility',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='utility',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='chatrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='chathistory',
            name='main_chathi_user_id_8788fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatrequest',
            name='main_chatre_user_id_0d019b_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatrequest',
            name='main_chatre_status_86fa37_idx',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatrequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='ai_actions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='chat_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='messages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='title',
            field=models.CharField(default='Новый чат', max_length=500),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='total_actions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='total_ai_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='total_user_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='action',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='chat_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='files_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='user_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='chatrequest',
            index=models.Index(fields=['status', 'created_at'], name='main_chatre_status_f415a1_idx'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeFolder',
        ),
        migrations.DeleteModel(
            name='FeedbackMessage',
        ),
        migrations.DeleteModel(
            name='InventoryFolder',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='ReceiptFile',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Utility',
        ),
    ]
