# Generated by Django 4.2.26 on 2025-12-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_main_chatreq_chat_re_idx_main_chatre_chat_re_525bb1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='category',
            field=models.CharField(choices=[('response_quality', 'Качество ответов'), ('action_performance', 'Выполнение действий'), ('performance', 'Производительность'), ('reliability', 'Надежность'), ('security', 'Безопасность'), ('user_experience', 'Пользовательский опыт'), ('file_processing', 'Обработка файлов'), ('data_accuracy', 'Точность данных'), ('calendar', 'Работа с календарем'), ('formatting', 'Форматирование'), ('user_engagement', 'Активность пользователей')], db_index=True, max_length=50),
        ),
    ]
