# Generated by Django 4.2.26 on 2025-12-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_metric_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='category',
            field=models.CharField(choices=[('response_quality', 'Качество ответов'), ('action_performance', 'Выполнение действий'), ('performance', 'Производительность'), ('reliability', 'Надежность'), ('security', 'Безопасность'), ('user_experience', 'Пользовательский опыт'), ('file_processing', 'Обработка файлов'), ('data_accuracy', 'Точность данных'), ('calendar', 'Работа с календарем'), ('formatting', 'Форматирование'), ('user_engagement', 'Активность пользователей'), ('request_analysis', 'Анализ запросов'), ('usage_patterns', 'Паттерны использования'), ('feature_usage', 'Использование функций'), ('content_analysis', 'Анализ контента'), ('multimodal', 'Мультимодальность'), ('satisfaction', 'Удовлетворенность')], db_index=True, max_length=50),
        ),
    ]
