# Generated by Django 4.2.26 on 2025-12-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_metric_chatrequestmetrics'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatrequestmetrics',
            new_name='main_chatre_chat_re_525bb1_idx',
            old_name='main_chatreq_chat_re_idx',
        ),
        migrations.RenameIndex(
            model_name='metric',
            new_name='main_metric_name_aed239_idx',
            old_name='main_metric_name_ca_idx',
        ),
        migrations.RenameIndex(
            model_name='metric',
            new_name='main_metric_categor_cd70bd_idx',
            old_name='main_metric_catego_idx',
        ),
        migrations.RenameIndex(
            model_name='metric',
            new_name='main_metric_period__7cc44e_idx',
            old_name='main_metric_period_idx',
        ),
    ]
