# Generated by Django 4.2.26 on 2025-12-02 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_metric_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('activity_type', models.CharField(choices=[('registration', 'Регистрация'), ('login', 'Вход'), ('chat_request', 'Запрос в чат'), ('page_view', 'Просмотр страницы'), ('feature_use', 'Использование функции'), ('file_upload', 'Загрузка файла'), ('calendar_action', 'Действие с календарем'), ('document_action', 'Действие с документом'), ('other', 'Другое')], db_index=True, max_length=50)),
                ('activity_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('chat_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='main.chatrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активность пользователя',
                'verbose_name_plural': 'Активности пользователей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='main_userac_user_id_171e32_idx'), models.Index(fields=['user_email', '-created_at'], name='main_userac_user_em_f57dd7_idx'), models.Index(fields=['activity_type', '-created_at'], name='main_userac_activit_55590f_idx'), models.Index(fields=['created_at'], name='main_userac_created_2e9351_idx')],
            },
        ),
    ]
