from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('cabinet/', views.cabinet, name='cabinet'),
    path('chat/', views.chat, name='chat'),
    path('api/chat/', views.chat_api, name='chat_api'),
    path('api/chat-status/<uuid:request_id>/', views.chat_status, name='chat_status'),
    path('api/check-lm-studio/', views.check_lm_studio_connection, name='check_lm_studio'),
    path('api/register/', views.register_user, name='register_user'),
    path('api/login/', views.login_api, name='login_api'),
    path('api/user-data/', views.get_user_data, name='get_user_data'),
    path('api/create-event/', views.create_calendar_event, name='create_calendar_event'),
    path('api/manage-calendar/', views.manage_calendar_event, name='manage_calendar_event'),
    path('api/chat-history/', views.get_chat_history, name='get_chat_history'),
    path('api/chat-history/<str:chat_id>/', views.get_chat_history_detail, name='get_chat_history_detail'),
    path('api/chat-history/<str:chat_id>/export/<str:format>/', views.export_chat_history, name='export_chat_history'),
    path('api/chat-history/<str:chat_id>/edit/', views.edit_chat_message, name='edit_chat_message'),
    path('api/export-chat-docx/', views.export_chat_docx_direct, name='export_chat_docx_direct'),
    path('transfer/', views.transfer, name='transfer'),
    path('receipts/', views.receipts, name='receipts'),
    path('utilities/', views.utilities, name='utilities'),
    path('taxes/', views.taxes, name='taxes'),
    path('calendar/', views.calendar, name='calendar'),
    path('documents/', views.documents, name='documents'),
    path('inventory/', views.inventory, name='inventory'),
    path('employees/', views.employees, name='employees'),
    path('support/', views.support, name='support'),
    path('mail/', views.mail, name='mail'),
    path('login/', views.login, name='login'),
    path('feedback/', views.feedback, name='feedback'),
    path('scenarios/', views.scenarios, name='scenarios'),
    path('api/error-log/', views.error_log, name='error_log'),
    path('api/metrics/', views.get_metrics, name='get_metrics'),
    path('api/metrics/calculate/', views.calculate_metrics, name='calculate_metrics'),
    path('api/metrics/summary/', views.get_metrics_summary, name='get_metrics_summary'),
]

